### ISSUE TITLE
[API] Query ERC20 contracts

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/trust-ray#227]
`/tokens/list?query=OMG`

Server-side we should be looking for smart contract name, symbol or address.

**Comment by vikmeup** [comment]
Add indexes for name, symbol

**Comment by kolya182** [comment]
@vikmeup Should it support `?query=OMG,ENG` ?.

**Comment by michaelScoff** [comment]
@kolya182 No need, just one name per query is good
