### ISSUE TITLE
Implement 721 parsing! Let's do it!

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/trust-ray#255]

**Comment by rraina** [comment]
I want to take a look — anyone want to point me to the most relevant files. 

Any other thoughts/pointers/watchouts before I start?

**Comment by vikmeup** [comment]
Can message me on telegram: vikmeup, this way we could tackle this faster

**Comment by elie222** [comment]
Would also be happy to help out here

**Comment by vikmeup** [comment]
@elie222 can you DM me on telegram: @vikmeup? or discord.

@johnnynanjiang is currently working on this, he might help out
