### ISSUE TITLE
Getting user balance for a token

### ISSUE THREAD

**Issue by elie222** [TrustWallet/trust-ray#287]
From looking at the `ApiRoutes.ts` file, I take it the API does not support individual balances at this time?

How does Trust wallet handle that side of things at the moment?

**Comment by kolya182** [comment]
It happens on client side.

**Comment by vikmeup** [comment]
@elie222 It’s done via RPC server on the client side. 

Balances should be client side, so it’s not depended on your node! We should always strive for decentralization and keep healthy balance between UX.

**Comment by vikmeup** [comment]
@elie222 take a look at documentation in here: https://github.com/TrustWallet/trust-ray/wiki/API#get-tokens-balanse-for-address
