### ISSUE TITLE
Fix Ubuntu setup for project

### ISSUE THREAD

**Issue by rip32700** [TrustWallet/trust-ray#29]
Following error occurs for ```$ npm install```

npm ERR! Linux 4.11.0-1013-azure
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm v3.5.2
...
npm ERR! Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild

**Comment by michaelScoff** [comment]
We have docker now
