### ISSUE TITLE
Add pending ERC20 balances to tokens endpoint

### ISSUE THREAD

**Issue by luisbebop** [TrustWallet/trust-ray#314]
It would be good to have pending ERC20 balances from an determined address.
Today when we have balances from an address, the output is:

```shell
curl https://api.trustwalletapp.com/tokens?address=0x99A8223C6535e945735ccd85f099281851C5c09B

{"docs":[{"balance":"11000000000000000000","contract":{"contract":"0x8a42c37558967da1fd2ff57969946320e61e9aab","address":"0x8a42c37558967da1fd2ff57969946320e61e9aab","name":"CloudWalkCoin","decimals":18,"symbol":"CWC"}}]}
```

Tokens appearing there have at least 1 confirmation.

If we could have pending balances from tokens that were just transferred but don't have 1 confirmation yet, this feature could be used by developers to create fast payment experiences. The developer could make a trade-off and assume the liability of double spending from small volume ERC20 token transactions.

The return would be something like this:

```shell
{"docs":[{"pending_balance":"2000000000000000000","balance":"11000000000000000000","contract":{"contract":"0x8a42c37558967da1fd2ff57969946320e61e9aab","address":"0x8a42c37558967da1fd2ff57969946320e61e9aab","name":"CloudWalkCoin","decimals":18,"symbol":"CWC"}}]}
```

**Comment by kolya182** [comment]
@luisbebop Hi, it's a great idea, do you use trust API for anything ?.

**Comment by luisbebop** [comment]
HI @kolya182 

Yes. I have been using `trust API` to process `ERC20` token payments in a point of sale.
In fact @vikmeup asked me to open this issue here.

Do you know how hard it would be to implement that and how long it would take?

**Comment by kolya182** [comment]
We use to have API that would provide pending transaction, i think it should not be difficult to implement, can you DM in telegram t.me/mykola ?

**Comment by luisbebop** [comment]
Yes sure!
