### ISSUE TITLE
How to start service with infura RPC url?

### ISSUE THREAD

**Issue by helloworld1991cn** [TrustWallet/trust-ray#338]
My app.json content:
`{
  "name": "Trust Wallet Backend",
  "description": "Backend API for the Trust Wallet App",
  "env": {
    "MONGODB_URI": {
      "description": "URI of your mongo DB.",
      "value": "mongodb://localhost:27017/trust-wallet"
    },
    "RPC_SERVER": {
      "description": "RPC URL of your blockchain node.",
      "value": "https://mainnet.infura.io/W6DbTwuISdes2JViQqGz"
    }
  }
}`

when i running Server.js, i got message:
`error: Error getPusherLatestBlock  "lastPusherBlock 0 ahead of lastBlock, waiting for new block in DB"
info: Pusher will retry in 5000
info: Forward ==> parsing blocks range 5978795 - 5985856. Difference 7062
info: Forward processing block 5978795
info: Forward processing block 5978796
info: <== Backward parsing blocks range 5978689 - 5985856. Difference 7166
info: Backward processing block 5978688
info: Backward processing block 5978689`

Is my parameter wrong, Please?

**Comment by kolya182** [comment]
@helloworld1991cn let me know if you still need a help, otherwise i will close this issue.

**Comment by helloworld1991cn** [comment]
@kolya182   unfortunately, it do not work. i use infura.io as RPC server, show msg "lastPusherBlock 0 ahead of lastBlock"

**Comment by kolya182** [comment]
@helloworld1991cn You need stop server and in MongoDB change value of `lastPusherBlock` lower than `lastBlock`

**Comment by helloworld1991cn** [comment]
@kolya182  sorry, I try again, run on production, but got msg:

error: Failed to load initial block state in getStatus: Error: Invalid JSON RPC response: ""

**Comment by kolya182** [comment]
Message me in Telegram t.me/mykola I will help

**Comment by kolya182** [comment]
How can I  dm you ?. Recently we stoped returning balance sit to high call volume. But yeah, let’s find way out for you.

**Comment by helloworld1991cn** [comment]
thank you. we can talk on email?  my email:thinksolos@gmail.com

**Comment by helloworld1991cn** [comment]
@kolya182  sorry, i have try more then 3 RPC nodes, always show msg: `error: Failed to load initial block state in getStatus: Error: Invalid JSON RPC response: ""`

my production.json contents is:
{
  "name": "Trust Wallet Backend",
  "description": "Backend API for the Trust Wallet App",
  "env": {
    "MONGODB_URI": {
      "description": "URI of your mongo DB.",
      "value": "mongodb://localhost:27017/trust-wallet"
    },
    "RPC_SERVER": {
      "description": "RPC URL of your blockchain node.",
      "value": "https://externally-advanced-bonefish.quiknode.io"
    }
  }
}

**Comment by kolya182** [comment]
[ ] Make sure `mongodb` up and running
[ ] Take a screenshot `lastparsedblocks` document in `mongodb`
[ ] Try use one this `RPC`: http://gasprice.poa.network:8545 or https://mainnet.infura.io/XyzEcUCJOQunP1PHWBJF

**Comment by helloworld1991cn** [comment]
@kolya182 sorry,  and I found the reasons at the end.
I always modify RPC URL in config/development.json or config/production.json, but the real config file is config/default.json ...  so it always response "JSON RPC response".
and now it is syncing...
thank you very much...

**Comment by helloworld1991cn** [comment]
![image](https://user-images.githubusercontent.com/2348232/43314855-cdadecdc-91c6-11e8-800a-ed51bdbf8bcb.png)

**Comment by nonren** [comment]
hi @kolya182,

im trying to use infura RPC url but yet it shows this error message. Please do advice what is the issue?

at=error code=H12 desc="Request timeout" method=GET path="/" host=techvus-wallet.herokuapp.com request_id=7a23b363-ee59-43ab-ac46-77d724eefbcc fwd="121.121.113.56" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https

**Comment by nonren** [comment]
Possible because of this issue?

error: Could not connect to Mongo with error: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]

**Comment by kolya182** [comment]
@nonren Make sure you have mongoDB installed, then in terminal run `mongod` to start the daemon

**Comment by kolya182** [comment]
Where do you look for data ?

**Comment by LoserTeach** [comment]
@kolya182 咨询一下有用吗？
