### ISSUE TITLE
Default distro in trust build is EOL

### ISSUE THREAD

**Issue by yellowmegaman** [TrustWallet/trust-ray#345]
Hello!

https://wiki.ubuntu.com/Releases

17.* are EOL, so it's really hard to deploy your app. 

Anything can be done about it? maybe official docker images?

Thanks a lot in advance!

**Comment by kolya182** [comment]
Try replace Ubuntu version for any is `current` in Dockerfile https://github.com/TrustWallet/trust-ray/blob/master/docker/Dockerfile

**Comment by yellowmegaman** [comment]
@kolya182 thanx for reply!
Didn't help much though https://pastebin.com/LQmGAd9h

**Comment by yellowmegaman** [comment]
Maybe i can use fresher version of Node/npm? Totally unfamiliar with nodejs

**Comment by kolya182** [comment]
@folex Will try to help you

**Comment by yellowmegaman** [comment]
Thank you!
Time was of the essence, so we've decided not to use TrustRay
