### ISSUE TITLE
How much time it will take to scan all transactions?

### ISSUE THREAD

**Issue by kelvinkuo** [TrustWallet/trust-ray#347]
I wrote scan program. it took too much time to scan whole blockchain. Main problem is geth can't response quickly. Parallel workers will cause "Error: Invalid JSON RPC response: """. I slow down the request.

So I want know how much time will trust-ray take to scan all transactions by now about 6111079 blocks

**Comment by kolya182** [comment]
Are using local RPC server ?.  I believe to sync a whole blockchain utilizing let say Infura RPC it may take up to 5 days. If you run Ray and RPC on the same machine (keep in mind you will need a lot of RAM and SSD disk for Geth to show some good performance).

**Comment by kolya182** [comment]
Are using local RPC server ?.  I believe to sync a whole blockchain utilizing let say Infura RPC it may take up to 5 days. If you run Ray and RPC on the same machine (keep in mind you will need a lot of RAM and SSD disk for Geth to show some good performance).

**Comment by kolya182** [comment]
let me know the results

**Comment by kelvinkuo** [comment]
I have a server with SSD disk and 8core CPU 16G RAM. I think its ok.
I will try websocket and batch request.

no problem, I will post the results.

**Comment by Boyjons74** [comment]
Super coin wallet!👍👍👍

**Comment by kelvinkuo** [comment]
@kolya182 batch request is the right way. I batch all getTransaction and getReceipt of one block. Speed goes up. about 4days, scanned all blocks.
Thanks

**Comment by kolya182** [comment]
How about RAM consumption ?.

**Comment by kelvinkuo** [comment]
For my program, memory is around 200MB. The bottleneck is geth. CPU usage goes high.
I need a schedule manager to get down RPC QPS.

**Comment by kelvinkuo** [comment]
I saw trust-ray uses abi-decoder, I encounter some transactions, It will raise exception when decoding the event logs. Like tx: 0x7834632fb74e671317e87551c5969dcf117efaf00c1f16c4e5d66419715e3b37.

I have reported the issue. But they haven't reply.

**Comment by kolya182** [comment]
I see your problem https://github.com/ConsenSys/abi-decoder/issues/27, i made PR long time ago https://github.com/ConsenSys/abi-decoder/pull/11 fixing it.
That why we do this  https://github.com/TrustWallet/trust-ray/blob/703192ca21666c7fa7fa9e5615b25db3c2c88460/package.json#L24

**Comment by kelvinkuo** [comment]
Thanks. abi-decoder long time no new commits.
