### ISSUE TITLE
Setting optimal parameters

### ISSUE THREAD

**Issue by flypaper0** [TrustWallet/trust-ray#367]
Hello,

Could you tell me please what these parameters affect, and what value should be passed to achieve the maximum synchronization speed?       

 ```
"DELAYS": {
            "FORWARD": "",
            "BACKWARD": ""
        },
"MAX_CONCURRENT_BLOCKS": ""
```

**Comment by kolya182** [comment]
@flypaper0 Hi Artur, sorry for the delay, those parameters set the delay in milliseconds between an attempt to parse next range of blocks. Set 1 ms to archive max speed, the default is `100` with respect to RPC provider like Infura. https://github.com/TrustWallet/trust-ray/blob/56b769e1ee27f42fe34a695ee0b60847266cba5d/src/common/BlockchainParser.ts#L22

`MAX_CONCURRENT_BLOCKS` responsible from how many blocks do you want to process at the time, default to 2, and set as many you want to keep in mind to respect RPC server you are using.
Play around tell us your observation on performance depends on configuration. https://github.com/TrustWallet/trust-ray/blob/56b769e1ee27f42fe34a695ee0b60847266cba5d/src/common/BlockchainParser.ts#L20
