### ISSUE TITLE
how to config my default.json

### ISSUE THREAD

**Issue by huyu6** [TrustWallet/trust-ray#368]
![image](https://user-images.githubusercontent.com/30172659/46927267-1d80f680-d067-11e8-8c8d-78131fa52afd.png)
"AWS": {
        "S3": {
            "ACCESSKEYID": "",
            "SECRETACCESSKEY": ""
        },
        "BUCKET": "",
        "BUCKET_BASE_URL": ""
    }
this config where to find???

**Comment by kolya182** [comment]
https://aws.amazon.com/s3/
