### ISSUE TITLE
启动server.js报错

### ISSUE THREAD

**Issue by LoserTeach** [trustwallet/trust-ray#373]
5|Server   | info: Pusher will retry in 5000
5|Server   | error: Error getPusherLatestBlock  "lastPusherBlock 0 ahead of lastBlock, waiting for new block in DB"
5|Server   | info: <== Backward parsing blocks range 1 - 1697473. Difference 1697471
5|Server   | info: Backward processing block 0
5|Server   | info: Backward processing block 1
5|Server   | error: Backword parsing failed for blocks 1 with error: 0. 
5|Server   | Restarting parsing for those blocks...
5|Server   | info: <== Backward parsing blocks range 1 - 1697473. Difference 1697471
5|Server   | info: Backward processing block 0
5|Server   | info: Backward processing block 1
5|Server   | error: Backword parsing failed for blocks 1 with error: 0.

**Comment by kolya182** [comment]
We move away for trust-ray and will archive repo soon, consider to use https://github.com/poanetwork/blockscout
