### ISSUE TITLE
Pull pending transactions from the RPC server

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-ray#53]
to make UX amazing for the user we would want to show pending transactions as well, for that we need to call 

https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbynumber, use `pending` as parameter 

@rip32700 I think this should be called when blockchain in sync and just checking for new blocks and etc.

**Comment by rip32700** [comment]
@michaelScoff will tackle this tonight

**Comment by kolya182** [comment]
Working on it.

**Comment by kolya182** [comment]
Closing due to https://github.com/TrustWallet/trust-ray/pull/75#issuecomment-355481766
