### ISSUE TITLE
Avoid adding null values for to or from fields

### ISSUE THREAD

**Issue by ghost** [trustwallet/trust-ray#55]
<img width="1678" alt="screen shot 2017-11-15 at 4 24 09 am" src="https://user-images.githubusercontent.com/32179653/32835948-f0336fde-c9bc-11e7-8989-2fa6c460bc01.png">

Doesn't hurt, but would be nice to have

Just flat map on addresses field I guess

**Comment by kolya182** [comment]
In case of contract creation https://etherscan.io/tx/0x5051473cc1cf2b934fc13e7863bd44b19392eae25f619f3d6653c89e30a55b1a `to` points contract address do you want replace with it ?.

**Comment by michaelScoff** [comment]
We should have a field `contract: String` on transaction mode, to will be empty string but make sure to remove null from addresses.

**Comment by kolya182** [comment]
Will replace `null` with `''`

**Comment by michaelScoff** [comment]
@kolya182 but also make sure null not being added to list of `addresses `
