### ISSUE TITLE
Parsing is behind 

### ISSUE THREAD

**Issue by michaelScoff** [TrustWallet/trust-ray#68]
Something happened and parser was behind

19.00 UTC - 20.30 UTC
`blocksToSync: 400`

**Comment by rip32700** [comment]
```blocksToSync: 0``` when I just checked.

**Comment by michaelScoff** [comment]
It’s not a solution to the problem! We need to find a cause

**Comment by michaelScoff** [comment]
https://kovan.trustwalletapp.com/
blocksToSync: 942,

**Comment by michaelScoff** [comment]
Closing. Issued related for nodes not being in sync and infura giving wrong information.

Status on fixing: https://github.com/paritytech/parity/issues/7065
